[package]
name = "user_lib"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.9.1"
buddy_system_allocator = "0.11.0"
lazy_static = { version = "1.5.0", features = ["spin_no_std"]}
riscv = { git = "https://github.com/rcore-os/riscv", features = ["inline-asm"] } 
